#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

EDITOR="vim"

# jenv
if type jenv >/dev/null ; then
  eval "$(jenv init - zsh)"
  export JAVA_HOME="$HOME/.jenv/versions/`jenv global`"
fi
