#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export EDITOR=vim
export VISUAL=$EDITOR

# Support certificate signing
if [ -f "/etc/pki/tls/certs/ca-bundle.crt" ]; then 
  export CURL_CA_BUNDLE="/etc/pki/tls/certs/ca-bundle.crt"
  alias brew="CURL_CA_BUNDLE='' brew" # brew might not work otherwise
fi

# jabba
[ -s "$HOME/.jabba/jabba.sh" ] && source "$HOME/.jabba/jabba.sh"

# nvm
export NVM_DIR="$HOME/.nvm"
if [ -d "$NVM_DIR" ]; then
  . "$(brew --prefix nvm)/nvm.sh"

  # place this after nvm initialization!
  autoload -U add-zsh-hook
  load-nvmrc() {
    local node_version="$(nvm version)"
    local nvmrc_path="$(nvm_find_nvmrc)"

    if [ -n "$nvmrc_path" ]; then
      local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

      if [ "$nvmrc_node_version" = "N/A" ]; then
        nvm install
      elif [ "$nvmrc_node_version" != "$node_version" ]; then
        nvm use
      fi
    elif [ "$node_version" != "$(nvm version default)" ]; then
      echo "Reverting to nvm default version"
      nvm use default
    fi
  }
  add-zsh-hook chpwd load-nvmrc
  load-nvmrc
fi

# rbenv
if type rbenv >/dev/null ; then
  eval "$(rbenv init -)"
fi

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if type pyenv >/dev/null ; then
  eval "$(pyenv init -)"
fi

# gradle
alias gw="./gradlew"
alias gww="./gradleww"

# local custom overrides
if [ -f "$HOME/.zprofile_local_only" ]; then
  source "$HOME/.zprofile_local_only"
fi

# zsh
unsetopt share_history
